package Modelo;

public enum Eventos {
    JUGADOR_AGREGADO,
    COMENZAR_JUEGO,
    DADOS_CON_PUNTOS,
    DADOS_SIN_PUNTOS,
    ACTUALIZACION_TURNO,
    DADOS_APARTADOS,
    DADOS_LANZADOS,
    ESCALERA_OBTENIDA,
    PLANTADO,
    JUGADOR_GANADOR,
    MAX_APARTADOS,
    INICIAR_LOBBY
}
